# Generated by Django 4.2.7 on 2026-01-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infrastructure.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_mercado_atual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moeda_origem', models.CharField(default='BRL', max_length=3)),
                ('natureza_bem', models.CharField(choices=[('P', 'Particular'), ('C', 'Comum')], max_length=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativo',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ativo')),
                ('cnpj_enc', models.CharField(max_length=500)),
                ('razao_social', models.CharField(max_length=255)),
                ('percentual_participacao', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.ativo',),
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ativo')),
                ('matricula', models.CharField(max_length=100)),
                ('iptu_index', models.CharField(max_length=100)),
                ('endereco_completo', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.ativo',),
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ativo')),
                ('tipo', models.CharField(max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('custodiante', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.ativo',),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ativo')),
                ('renavam_enc', models.CharField(max_length=500)),
                ('placa', models.CharField(max_length=10)),
                ('modelo_ano', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.ativo',),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', infrastructure.db.fields.EncryptedDataField(max_length=500, verbose_name='CPF')),
                ('data_nascimento', models.DateField()),
                ('regime_bens', models.CharField(blank=True, choices=[('CP', 'Comunhão Parcial'), ('CU', 'Comunhão Universal'), ('SB', 'Separação de Bens'), ('PF', 'Participação Final nos Questos')], max_length=2, null=True)),
                ('conjuge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_mae', to='core.pessoa')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_pai', to='core.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=10)),
                ('tabela', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(max_length=100)),
                ('payload_antes', models.JSONField(null=True)),
                ('payload_depois', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='core.pessoa'),
        ),
    ]
