# Generated by Django 6.0.1 on 2026-01-19 01:00

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType


def migrate_proprietario_to_generic(apps, schema_editor):
    """
    Data migration: Convert existing Ativo.proprietario (Pessoa FK) 
    to GenericForeignKey (content_type + object_id)
    """
    Ativo = apps.get_model('core', 'Ativo')
    Pessoa = apps.get_model('core', 'Pessoa')
    ContentTypeModel = apps.get_model('contenttypes', 'ContentType')
    
    # Get ContentType for Pessoa
    try:
        pessoa_ct = ContentTypeModel.objects.get(app_label='core', model='pessoa')
    except ContentTypeModel.DoesNotExist:
        # If ContentType doesn't exist yet, create it
        pessoa_ct = ContentTypeModel.objects.create(app_label='core', model='pessoa')
    
    # Update all existing Ativos
    for ativo in Ativo.objects.select_related('proprietario_old').all():
        if hasattr(ativo, 'proprietario_old') and ativo.proprietario_old:
            ativo.content_type = pessoa_ct
            ativo.object_id = ativo.proprietario_old.id
            ativo.save(update_fields=['content_type', 'object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_familia_pessoa_familia'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Step 1: Rename old FK temporarily
        migrations.RenameField(
            model_name='ativo',
            old_name='proprietario',
            new_name='proprietario_old',
        ),
        
        # Step 2: Add new GenericFK fields (nullable for now)
        migrations.AddField(
            model_name='ativo',
            name='content_type',
            field=models.ForeignKey(
                null=True,  # Temporary
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AddField(
            model_name='ativo',
            name='object_id',
            field=models.UUIDField(null=True),  # Temporary
        ),
        
        # Step 3: Data migration
        migrations.RunPython(migrate_proprietario_to_generic, reverse_code=migrations.RunPython.noop),
        
        # Step 4: Remove old FK
        migrations.RemoveField(
            model_name='ativo',
            name='proprietario_old',
        ),
        
        # Step 5: Make new fields non-nullable
        migrations.AlterField(
            model_name='ativo',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
