# Generated by Django 6.0.1 on 2026-01-19 01:00

import django.core.validators
import django.db.models.deletion
import infrastructure.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convert_ativo_to_genericfk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='natureza_bem',
            field=models.CharField(choices=[('P', 'Particular'), ('C', 'Comum')], help_text='COMUM: Adquirido durante o casamento (sofre meação). PARTICULAR: Anterior ao casamento, herança ou doação (não sofre meação).', max_length=1),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', infrastructure.db.fields.EncryptedDataField(max_length=500, verbose_name='CNPJ')),
                ('tipo_societario', models.CharField(choices=[('LTDA', 'Sociedade Limitada'), ('SA', 'Sociedade Anônima'), ('EIRELI', 'Empresa Individual de Responsabilidade Limitada'), ('SLU', 'Sociedade Limitada Unipessoal')], default='LTDA', max_length=10)),
                ('data_constituicao', models.DateField(verbose_name='Data de Constituição')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.familia')),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoHolding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de participação (ex: 50.00 para 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tipo_quota', models.CharField(choices=[('ORD', 'Ordinária'), ('PREF', 'Preferencial')], default='ORD', max_length=4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='core.holding')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Participação em Holding',
                'verbose_name_plural': 'Participações em Holdings',
                'unique_together': {('pessoa', 'holding')},
            },
        ),
    ]
