# Generated by Django 6.0.1 on 2026-01-19 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_endereco_alter_holding_cnpj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoImagem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('imagem', models.ImageField(upload_to='anexos/%Y/%m/', verbose_name='Imagem')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografia'), ('DOC', 'Documento'), ('ESCRIT', 'Escritura'), ('RG', 'RG/CPF'), ('MATRICULA', 'Matrícula'), ('IPTU', 'IPTU'), ('RENAVAM', 'Renavam'), ('OUTRO', 'Outro')], default='FOTO', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo/Imagem',
                'verbose_name_plural': 'Anexos/Imagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
