# Generated by Django 4.2.7 on 2026-01-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anexoimagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='modelo_ano',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(default=2024, verbose_name='Ano Fabricação'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Modelo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='codigo_fipe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código FIPE'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(default='Carros', max_length=50, verbose_name='Tipo (Carro/Moto)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam_enc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Renavam'),
        ),
    ]
