# Generated by Django 4.2.7 on 2026-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_veiculo_options_remove_veiculo_modelo_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros/', verbose_name='Foto do Perfil'),
        ),
    ]
