# Generated by Django 5.2.12 on 2026-04-02 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_familiaacesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'EndereÃ§o', 'verbose_name_plural': 'EndereÃ§os'},
        ),
        migrations.AlterModelOptions(
            name='familiaacesso',
            options={'verbose_name': 'Acesso de FamÃƒÂ\xadlia', 'verbose_name_plural': 'Acessos de FamÃƒÂ\xadlia'},
        ),
        migrations.AlterModelOptions(
            name='participacaoholding',
            options={'verbose_name': 'ParticipaÃ§Ã£o em Holding', 'verbose_name_plural': 'ParticipaÃ§Ãµes em Holdings'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'VeÃ\xadculo', 'verbose_name_plural': 'VeÃ\xadculos'},
        ),
        migrations.AddField(
            model_name='familia',
            name='inventario_prazo_final',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo final do inventario'),
        ),
        migrations.AddField(
            model_name='familia',
            name='itcmd_uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'AmapÃ¡'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'CearÃ¡'), ('DF', 'Distrito Federal'), ('ES', 'EspÃ\xadrito Santo'), ('GO', 'GoiÃ¡s'), ('MA', 'MaranhÃ£o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'ParÃ¡'), ('PB', 'ParaÃ\xadba'), ('PR', 'ParanÃ¡'), ('PE', 'Pernambuco'), ('PI', 'PiauÃ\xad'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'RondÃ´nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'SÃ£o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF de referencia do ITCMD'),
        ),
        migrations.AddField(
            model_name='familia',
            name='itcmd_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Proximo vencimento do ITCMD'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu_valor_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='IPTU anual'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Proximo vencimento do IPTU'),
        ),
        migrations.AlterField(
            model_name='anexoimagem',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='anexoimagem',
            name='tipo',
            field=models.CharField(choices=[('FOTO', 'Fotografia'), ('DOC', 'Documento'), ('ESCRIT', 'Escritura'), ('RG', 'RG/CPF'), ('MATRICULA', 'MatrÃ\xadcula'), ('IPTU', 'IPTU'), ('RENAVAM', 'Renavam'), ('OUTRO', 'Outro')], default='FOTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='natureza_bem',
            field=models.CharField(choices=[('P', 'Particular'), ('C', 'Comum')], help_text='COMUM: Adquirido durante o casamento (sofre meaÃ§Ã£o). PARTICULAR: Anterior ao casamento, heranÃ§a ou doaÃ§Ã£o (nÃ£o sofre meaÃ§Ã£o).', max_length=1),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='NÃºmero'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'AmapÃ¡'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'CearÃ¡'), ('DF', 'Distrito Federal'), ('ES', 'EspÃ\xadrito Santo'), ('GO', 'GoiÃ¡s'), ('MA', 'MaranhÃ£o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'ParÃ¡'), ('PB', 'ParaÃ\xadba'), ('PR', 'ParanÃ¡'), ('PE', 'Pernambuco'), ('PI', 'PiauÃ\xad'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'RondÃ´nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'SÃ£o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Familia/Caso'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='data_constituicao',
            field=models.DateField(verbose_name='Data de ConstituiÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='tipo_societario',
            field=models.CharField(choices=[('LTDA', 'Sociedade Limitada'), ('SA', 'Sociedade AnÃ´nima'), ('EIRELI', 'Empresa Individual de Responsabilidade Limitada'), ('SLU', 'Sociedade Limitada Unipessoal')], default='LTDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco_completo',
            field=models.TextField(blank=True, verbose_name='EndereÃ§o (legado)'),
        ),
        migrations.AlterField(
            model_name='participacaoholding',
            name='percentual',
            field=models.DecimalField(decimal_places=2, help_text='Percentual de participaÃ§Ã£o (ex: 50.00 para 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='participacaoholding',
            name='tipo_quota',
            field=models.CharField(choices=[('ORD', 'OrdinÃ¡ria'), ('PREF', 'Preferencial')], default='ORD', max_length=4),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='regime_bens',
            field=models.CharField(blank=True, choices=[('CP', 'ComunhÃ£o Parcial'), ('CU', 'ComunhÃ£o Universal'), ('SB', 'SeparaÃ§Ã£o de Bens'), ('PF', 'ParticipaÃ§Ã£o Final nos Questos')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(default=2024, verbose_name='Ano FabricaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='codigo_fipe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CÃ³digo FIPE'),
        ),
    ]
